### ISSUE TITLE
buildpack doesn't use a Windows/Linux crossplatform Gemfile.lock

### ISSUE THREAD

**Issue by pivotalgeorge** [cloudfoundry/ruby-buildpack#100]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```sh
{                                                                                    
   "name": "",                                                                       
   "build": "",                                                                      
   "support": "https://support.pivotal.io",                                          
   "version": 0,                                                                     
   "description": "",                                                               
    ... ,                   
   "min_cli_version": "6.23.0",                                                      
   "min_recommended_cli_version": "6.23.0",                                          
   "api_version": "2.94.0",
    [redacted]  
}                                                                                    
```

What version of the buildpack you are using?
1.7.11 and 1.7.15

If you were attempting to accomplish a task, what was it you were attempting to do?
What did you expect to happen?
What was the actual behavior?

we have a ruby application that runs on both windows (dev machines) and linux (pcf)
when pushing to cf, we get the WARNING
```
Removing `Gemfile.lock` because it was generated on Windows.
```
Our bundle-generated `Gemfile.lock` contained both `ruby` and `x64-mingw32`  as PLATFORMS, and had LF line endings. Our `Gemfile.lock` looks like:
```
GEM
  remote: https://rubygems.org/
  specs:
    mustermann (1.0.2)
    rack (2.0.5)
    rack-protection (2.0.1)
      rack
    sinatra (2.0.1)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.1)
      tilt (~> 2.0)
    tilt (2.0.8)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  rack
  sinatra

BUNDLED WITH
   1.16.1
```

When using an identical (except for the `x64-mingw32` line) `Gemfile.lock`, the app deployed and ran successfully, with no warnings from the buildpack or bundler. In other words, to reproduce:
1. create a Gemfile with some gems, e.g.
```rb
gem "sinatra"
gem "rack"
```
1. create a cf manifest with:
```yml
applications:
- name: demo
  buildpack: ruby_buildpack
```
1. `bundle` on linux
1. `bundle` on windows
1. `cf push`

We believe our original, cross-platform `Gemfile.lock` would have worked (since we ran bundle on linux as well) if the buildpack had not chosen to ignore it.

One possible fix would be to replace the logic that detects presence of windows in `Gemfile.lock`s with `bundle --frozen`, which should:
- ignore windows gems as the command is being run on a different platform (normal bundler behavior)
- exit nonzero if the command would require a `Gemfile.lock` file change

We think we found the offending bits: https://github.com/cloudfoundry/ruby-buildpack/blob/84e9b6ecda79b04c3dd02cd7c369566667c6a028/src/ruby/supply/supply.go#L557-L565 and https://github.com/cloudfoundry/ruby-buildpack/blob/8a4c82f2d00534d7773750a33a5363a04d47f16d/src/ruby/versions/ruby.go#L166

Please confirm where necessary:
* [ ] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by tylerphelan** [comment]
@pivotalgeorge Is this a repeat of https://github.com/cloudfoundry/ruby-buildpack/issues/99? If so, I'll close this one and we'll use the other.
