### ISSUE TITLE
Failed to compile droplet rails app status 223

### ISSUE THREAD

**Issue by briannarelucio** [cloudfoundry/ruby-buildpack#104]
Hello! Im trying to push a rails app and I keep getting this error, any advice on how to fix this? 

`Waiting for API to complete processing files...

Staging app and tracing logs...
   Downloading dotnet_core_buildpack...
   Downloading nodejs_buildpack...
   Downloading java_buildpack_large_heap...
   Downloading staticfile_buildpack...
   Downloading go_buildpack...
   Downloaded nodejs_buildpack
   Downloading java_buildpack...
   Downloaded java_buildpack_large_heap (958.4K)
   Downloading php_buildpack...
   Downloaded java_buildpack (160.7K)
   Downloading python_buildpack...
   Downloaded staticfile_buildpack (2.6M)
   Downloading predix_openresty_buildpack...
   Downloaded predix_openresty_buildpack (13.7M)
   Downloading ruby_buildpack...
   Downloaded ruby_buildpack (280.2M)
   Downloading matlab_buildpack_r2015a...
   Downloaded python_buildpack (296.8M)
   Downloading java-buildpack...
   Downloaded java-buildpack (173.6K)
   Downloading matlab_buildpack_r2011b...
   Downloaded go_buildpack (392M)
   Downloading binary_buildpack...
   Downloaded binary_buildpack (49.1K)
   Downloading matlab_buildpack_r2012a...
   Downloaded dotnet_core_buildpack (437.4M)
   Downloading java-offline-buildpack...
   Downloaded matlab_buildpack_r2011b (323.1M)
   Downloaded php_buildpack (419M)
   Downloaded matlab_buildpack_r2015a (814M)
   Downloaded matlab_buildpack_r2012a (279.9M)
   Downloaded java-offline-buildpack (244.5M)
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (5.6M)
   Staging...
   -------> Buildpack version 1.6.34
          Downloaded [file:///tmp/buildpacks/3025dd0089b688d8fdbc9c7a68192c7b/dependencies/https___buildpacks.cloudfoundry.org_dependencies_bundler_bundler-1.14.3-cddcef74.tgz]
   -----> Compiling Ruby/Rails
          Downloaded [file:///tmp/buildpacks/3025dd0089b688d8fdbc9c7a68192c7b/dependencies/https___buildpacks.cloudfoundry.org_dependencies_ruby_ruby-2.4.0-linux-x64-e6c8fe11.tgz]
   -----> Using Ruby version: ruby-2.4.0
   ###### WARNING:
          You have the `.bundle/config` file checked into your repository
          It contains local state like the location of the installed bundle
          as well as configured git local gems, and other settings that should
          not be shared between multiple checkouts of a single repo. Please
          remove the `.bundle/` folder from your repo and add it to your `.gitignore` file.
   -----> Installing dependencies using bundler 1.14.3
          Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
          Warning: the running version of Bundler (1.14.3) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
          Fetching gem metadata from https://rubygems.org/.........
          Fetching version metadata from https://rubygems.org/..
          Fetching dependency metadata from https://rubygems.org/.
          Installing minitest 5.11.3
          Installing rake 12.3.1
          Installing concurrent-ruby 1.0.5
          Installing thread_safe 0.3.6
          Installing erubi 1.7.1
          Installing builder 3.2.3
          Installing mini_portile2 2.3.0
          Installing crass 1.0.4
          Installing rack 2.0.5
          Installing nio4r 2.3.1 with native extensions
          Installing websocket-extensions 0.1.3
          Installing mini_mime 1.0.0
          Installing arel 9.0.0
          Installing mimemagic 0.3.2
          Installing execjs 2.7.0
          Installing rb-fsevent 0.10.3
          Installing msgpack 1.2.4 with native extensions
          Installing ffi 1.9.25 with native extensions
          Installing coffee-script-source 1.12.2
          Installing method_source 0.9.0
          Installing thor 0.20.0
          Installing multi_json 1.13.1
          Installing puma 3.11.4 with native extensions
          Using bundler 1.14.3
          Installing tilt 2.0.8
          Installing sqlite3 1.3.13 with native extensions
          Installing turbolinks-source 5.1.0
          Installing i18n 1.0.1
          Installing tzinfo 1.2.5
          Installing nokogiri 1.8.3 with native extensions
          Installing rack-test 1.0.0
          Installing sprockets 3.7.2
          Installing websocket-driver 0.7.0 with native extensions
          Installing mail 2.7.0
          Installing marcel 0.3.2
          Installing autoprefixer-rails 8.6.3
          Installing uglifier 4.1.12
          Installing coffee-script 2.4.1
          Installing bootsnap 1.3.0 with native extensions
          Installing rb-inotify 0.9.10
          Installing turbolinks 5.1.1
          Installing activesupport 5.2.0
          Installing loofah 2.2.2
          Installing sass-listen 4.0.0
          Installing rails-dom-testing 2.0.3
          Installing globalid 0.4.1
          Installing activemodel 5.2.0
          Installing jbuilder 2.7.0
          Installing activejob 5.2.0
          Installing actionview 5.2.0
          Installing bootstrap-sass 3.3.7
          Installing rails-html-sanitizer 1.0.4
          Installing sass 3.5.6
          Installing activerecord 5.2.0
          Installing actionpack 5.2.0
          Installing actionmailer 5.2.0
          Installing actioncable 5.2.0
          Installing activestorage 5.2.0
          Installing sprockets-rails 3.2.1
          Installing simple_form 4.0.1
          Installing railties 5.2.0
          Installing coffee-rails 4.2.2
          Installing sass-rails 5.0.7
          Bundle complete! 20 Gemfile dependencies, 64 gems now installed.
          Gems in the groups development, test and production were not installed.
          Bundled gems are installed into ./vendor/bundle.
          Bundle completed (62.49s)
          Cleaning up the bundler cache.
          Installing rails 5.2.0
   WARNING: node 4 will no longer be available in new buildpacks released after 2018-04-01
   -----> Preparing app for Rails asset pipeline
          Running: rake assets:precompile
          Yarn executable was not detected in the system.
          Download Yarn at https://yarnpkg.com/en/docs/install
          I, [2018-06-22T21:39:01.896359 #4125]  INFO -- : Writing /tmp/app/public/assets/application-e3aea9ccc8ceb6f6ac49f92e8e44cc360bea2ccc0ad478c958231f1bf16bc9e3.js
          I, [2018-06-22T21:39:01.896922 #4125]  INFO -- : Writing /tmp/app/public/assets/application-e3aea9ccc8ceb6f6ac49f92e8e44cc360bea2ccc0ad478c958231f1bf16bc9e3.js.gz
          rake aborted!
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:278:in `sprockets_context'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:124:in `asset_path'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:200:in `font_path'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:155:in `block in _perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `block in with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:416:in `visit_return'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:265:in `block (3 levels) in perform_sass_fn'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:265:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:264:in `block in perform_sass_fn'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:86:in `perform_arguments'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:261:in `perform_sass_fn'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:144:in `block in _perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `block in with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:143:in `_perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/functions.rb:617:in `perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:155:in `block in _perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `block in with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:186:in `perform_arg'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:516:in `visit_directive'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:467:in `visit_atroot'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:88:in `block in with_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:88:in `with_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:161:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
          NoMethodError: undefined method `[]' for nil:NilClass
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:153:in `_perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:10:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:265:in `block (2 levels) in perform_sass_fn'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:264:in `catch'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/node.rb:50:in `perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/functions.rb:2391:in `if'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:108:in `with_function'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:153:in `_perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `block in _perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `each_with_index'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/script/tree/funcall.rb:133:in `_perform'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:402:in `visit_prop'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:517:in `block (2 levels) in visit_directive'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:517:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:517:in `block in visit_directive'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:88:in `with_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `block in with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:88:in `block in with_import'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:135:in `with_frame'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/stack.rb:79:in `with_base'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:162:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `map'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:52:in `visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `block in visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/base.rb:36:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/visitors/perform.rb:10:in `visit'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/root_node.rb:36:in `css_tree'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/tree/root_node.rb:20:in `render'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sass-3.5.6/lib/sass/engine.rb:290:in `render'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:48:in `call'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
          /tmp/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
          Tasks: TOP => assets:precompile
          (See full trace by running task with --trace)
    **!
    !     Precompiling assets failed.
    !
   Failed to compile droplet
   Exit status 223
   Staging failed: Exited with status 223
   Destroying container
   Successfully destroyed container
Error staging application: App staging failed in the buildpack compile phase
FAILED**
`

**Comment by sclevine** [comment]
Can you try with the latest buildpack version? The version you’re using doesn’t have yarn (which may be the issue here), and also only supplies old versions of ruby that are likely vulnerable to many known CVEs.

**Comment by astrieanna** [comment]
@briannarelucio Did you try this with the latest buildpack version?

**Comment by jfeeny** [comment]
@briannarelucio We're going to go ahead and close this issue for now, but feel free to reopen it if you have more questions.

**Comment by javaHelper** [comment]
I am getting the error:

```
Staging app and tracing logs...
   Downloading java_buildpack_offline...
   Downloaded java_buildpack_offline
   Cell d6fadf88-b844-4d18-ba3b-1d1ed9cb72e7 creating container for instance 4bd27749-d91e-441d-9bff-53c35d35e9f1
   Cell d6fadf88-b844-4d18-ba3b-1d1ed9cb72e7 successfully created container for instance 4bd27749-d91e-441d-9bff-53c35d35e9f1
   Downloading app package...
   Downloaded app package (164.3K)
   [1m[31m----->[0m[22m [1m[34mJava Buildpack[0m[22m [34mv4.26[0m [34m(offline)[0m | https://github.com/cloudfoundry/java-buildpack.git#e06e00b
   [Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
   No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. 
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
   Cell d6fadf88-b844-4d18-ba3b-1d1ed9cb72e7 stopping instance 4bd27749-d91e-441d-9bff-53c35d35e9f1
   Cell d6fadf88-b844-4d18-ba3b-1d1ed9cb72e7 destroying container for instance 4bd27749-d91e-441d-9bff-53c35d35e9f1
   Cell d6fadf88-b844-4d18-ba3b-1d1ed9cb72e7 successfully destroyed container for instance 4bd27749-d91e-441d-9bff-53c35d35e9f1
Error staging application: App staging failed in the buildpack compile phase
FAILED
```
