### ISSUE TITLE
/src/ruby/supply/supply.go captures all output from rake secret instead of the last line.

### ISSUE THREAD

**Issue by innov8d** [cloudfoundry/ruby-buildpack#105]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

min_cli_version: "6.23.0"
min_recommended_cli_version: "6.23.0"
api_version": "2.98.0"
cf version 6.26.0+9c9a261fd.2017-04-06

**What version of the buildpack you are using?**

https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.18

**If you were attempting to accomplish a task, what was it you were attempting to do?**

Deploy an jruby rails application to CF using ruby buildpack. The app displays logging output when the command `bundle exec rake secret` is run and it is being included in `profile.d/0_ruby.sh`. Right now that just causes non-fatal errors to be displayed when container is started, but this could be used by a developer to inject arbitrary commands into the `profile.d/0_ruby.sh`.

Example profile.d file: [0_java.txt](https://github.com/cloudfoundry/ruby-buildpack/files/2228862/0_java.txt)
Example errors when additional text is captured: [error.txt](https://github.com/cloudfoundry/ruby-buildpack/files/2228893/error.txt)
Source file with issue: [/src/ruby/supply/supply.go](https://github.com/cloudfoundry/ruby-buildpack/blob/77c0554aa5db312254b8c473c0a2f06fd9b96d0b/src/ruby/supply/supply.go#L784)

**What did you expect to happen?**

Expect `profile.d/0_ruby.sh` to run without errors during container startup. Expect parsing of `bundle exec rake secret` to only use the last line of the output.

**What was the actual behavior?**

Errors are displayed due to log text from `bundle exec rake secret` being included in `profile.d/0_ruby.sh`

Please confirm where necessary:
* [ x ] I have included a log output
* [ x ] My log includes an error message
* [ x ] I have included steps for reproduction

**Comment by astrieanna** [comment]
@innov8d 👍
