### ISSUE TITLE
Remove non-web default processes

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/ruby-buildpack#107]
CF is moving closer to providing Procfile support by default.

The non-web processes that this buildpack provide -- `console` and `rake` -- do not make sense in a CF context. 

I think we should remove them in the CF version of this buildpack.

Would like to get your thoughts and offer to submit a PR if that would help.

thanks!

**Comment by Zanadar** [comment]
Thanks for the issue @zrob . We agree!  Removed these non-web defaults with https://github.com/cloudfoundry/ruby-buildpack/commit/28d4a06a3651b9e43d664ae4c0f9f8dc7c73b8b6 on develop.

**Comment by Zanadar** [comment]
Closing as fixed.
