### ISSUE TITLE
Support Ruby 2.6.2

### ISSUE THREAD

**Issue by seadowg** [cloudfoundry/ruby-buildpack#109]
Ruby 2.6.2 released a few days ago. Great to get support added in the buildpack!

**Comment by shanks3012** [comment]
@seadowg 

The next release of the Ruby buildpack will include 2.6.2. If you would like to use it now, it exists on the develop branch!

Thanks!

Elliott Shanks
CF Buildpacks PM

**Comment by seadowg** [comment]
Amazing thanks 👍
