### ISSUE TITLE
NOTICE: [ruby-buildpack] End of support for Ruby versions 2.2.x and 2.3.x after May 11, 2019

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/ruby-buildpack#112]
The first release of the Ruby buildpack after May 11, 2019 will no longer include any versions of Ruby 2.2.x and 2.3.x. These Ruby versions are no longer supported upstream [1]. Please migrate your Ruby apps to supported versions of Ruby before that time. 

Note: Unless you are manually specifying a version of Ruby for the buildpack to use, or you have customized your Ruby buildpack, no action is required.

[1] https://www.ruby-lang.org/en/downloads/branches/

Thanks,
Elliott Shanks, CF Buildpacks PM

**Comment by kardolus** [comment]
Note that rails3 will no longer work after we make this change. Rails3 requires <= ruby 2.3
