### ISSUE TITLE
ruby 2.6.3 came out 4/17 but its not in manifest.yml

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/ruby-buildpack#113]
https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released/

**Comment by drnic** [comment]
Looks like CI failing https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/create-ruby-2.6.X-story/builds/6

**Comment by drnic** [comment]
Perhaps add slack notification if errors in pipeline bumping security fixes to buildpacks?

**Comment by kardolus** [comment]
@drnic thanks for pointing this out. We had a race condition in our CI. Fixed. Ruby version was added in this commit: https://github.com/cloudfoundry/ruby-buildpack/commit/fca8745a185fc09760cf848f91b72c128a1ec661
