### ISSUE TITLE
[ruby-buildpack] Support for Ruby 2.4.9

### ISSUE THREAD

**Issue by tulaseerao** [cloudfoundry/ruby-buildpack#118]
What version of the buildpack you are using?
v1.8.4

We are using ruby 2.4.9 (rails 4+) for our apps running on IBM cloud and thinking of migrating to rails 5/ruby 2.5.6 after couple of months.  We need sometime to rewrite some rails/ruby libraries and just wondering about actual end support for ruby 2.4.9. 

Please see let me know actual end support for 2.4.9 and we will plan accordingly from our side.

**Comment by ForestEckhardt** [comment]
Ruby 2.4.x version will be removed from the buildpack for versions released after April 1, 2020.
