### ISSUE TITLE
Ruby-buildpack-v1.8.1 contains a file under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License?

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/ruby-buildpack#121]
Hi, I'm referring to CF Deployment **12.2** and ruby-buildpack-v1.8.1.

Ruby-buildpack-v1.8.1, in https://github.com/cloudfoundry/ruby-buildpack/blob/v1.8.1/manifest.yml, include 
ruby version: 2.5.6
uri: https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.6-linux-x64-cflinuxfs3-1edf7db5.tgz

and this blob include the file **"incorrect_words.yaml",** in the path ruby-2.5.6-linux-x64-cflinuxfs3-1edf7db5/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/evaluation

The same for 
ruby version: 2.5.7
uri: https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.7-linux-x64-cflinuxfs3-01b7d7a8.tgz.

Now, I've seen that the file **"incorrect_words.yaml"** has this header:

** More specifically, this is a yaml version of the data in FAWTHROP1DAT.643 and FAWTHROP2DAT.643.
# released under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
  https://creativecommons.org/licenses/by-nc-sa/3.0/**
---
So, it seems that also this file is under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License and this is a license not acceptable in a commercial product. 

Could you please clarify and confirm if ruby-buildpack 1.8.1 does really contain NonCommercial Code?

Thanks.

**Comment by luisapace** [comment]
Hi, do you have any news on this?

**Comment by flavorjones** [comment]
See for reference https://github.com/ruby/did_you_mean/issues/105

**Comment by flavorjones** [comment]
Context: Since Ruby 2.3, the basic Ruby distribution vendors the `did_you_mean` gem.

Based on the above linked-to issue, did_you_mean v1.2.1 and later do not have this file. Ruby was updated to use v1.2.1 in commit https://github.com/ruby/ruby/commit/1658fb3 which was first released in Ruby `v2_6_0_preview2`.

Thus my very quick investigation shows that yes, any ruby buildpack containing a version of Ruby < 2.6.0 will contain this file.

**Comment by luisapace** [comment]
Thanks a lot. I'm going to contact our attorney to ask how to manage this: in view of that, could be possible to know:

- if you are planning any activity to solve this, and 
- what are the versions of ruby-buildpack that are safe so we can verify their installation instead of that affected by this issue? 

Thanks.

**Comment by dwillist** [comment]
@luisapace Looks like the file that contains this license is only used to test & benchmark the code in question. Here: https://github.com/ruby/did_you_mean/blob/e5c481e64ca07ed05dbfc9768631d9270a05f5b1/evaluation/calculator.rb#L53

**Comment by luisapace** [comment]
@dwillist Even if the file is only used for test but it's contained in the distributions of ruby we still have the problem; could you please confirm if it is contained OR not in the distributions of ruby version specified at https://github.com/cloudfoundry/ruby-buildpack/blob/v1.8.1/manifest.yml?

I mean: ruby 2.4.8, 2.4.9, 2.5.6, 2.5.7, 2.6.4, 2.6.5

I've found the problem in ruby 2.4.8, 2.4.9, 2.5.6 and 2.5.7 as confirmed also by Mike above, but I kindly ask if you can verify also for ruby 2.6.4 and 2.6.5.

Thanks

**Comment by luisapace** [comment]
@dwillist @flavorjones Hi, may I kindly ask you if could you please confirm if it the file "incorrect_words.yaml", is contained OR not in the distributions of ruby versions specified at https://github.com/cloudfoundry/ruby-buildpack/blob/v1.8.1/manifest.yml?

I mean: ruby 2.4.8, 2.4.9, 2.5.6, 2.5.7, 2.6.4, 2.6.5

I've found the problem in ruby 2.4.8, 2.4.9, 2.5.6 and 2.5.7 as confirmed also by Mike above, but I kindly ask if you can verify also for ruby 2.6.4 and 2.6.5. 

I apologize to disturb you again, but depending on your answer we will have to do different action, so you feedback here is fundamental. Thanks again for your collaboration!

**Comment by dwillist** [comment]
@luisapace ruby `2.6.4` and `2.6.5` both use the `did_you_mean` gem version `1.3.0` which has removed the `incorrect_words.yaml` file.

In the future an audit for this file in `2.6.4` and `2.6.5` could be preformed using a simple [`find`](https://linux.die.net/man/1/find) command.

**Comment by luisapace** [comment]
@dwillist Hi Daniel, thanks for your comment.

PS. I'm confused on last sentence: why in the future should I perform an audit on those levels, if they do not include the bad file? could you please clarify?

**Comment by sclevine** [comment]
Closing and moving conversation to #123. 2.6.x do not contain the file.
