### ISSUE TITLE
what is the Ruby-buildpack without the file under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License?

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/ruby-buildpack#123]
Based on your last comments on the issue:

https://github.com/cloudfoundry/ruby-buildpack/issues/121

I've verified that the last Ruby-buildpack availailable (1.8.14) still contain the ruby versions affected by the file under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License ("incorrect_words.yaml" from did_you_mean-1.2.0).

**I kindly ask you to indicate when you plan to release a level of ruby-buildpack free of this issue and - in the meantime - the actions you suggest to do to eliminate this problem.**

Thanks.

**Comment by sclevine** [comment]
We do not plan to release a ruby-buildpack without the file in question until all versions of ruby that contain the file are EOL. While there is no published EOL for Ruby 2.5, if it follows past versions of ruby, that date will likely be 2021-03-31.

The license in question does not appear to affect distribution of the buildpack, but CFF legal could be asked to review. (CC: @christopherclark)

**Comment by luisapace** [comment]
@sclevine Hi, may I kindly ask you to clarify what you mean with: "The license in question does not appear to affect distribution of the buildpack" ? thanks

**Comment by sclevine** [comment]
You are correct the licensed files are included in offline packaged versions of the buildpack.

However, my understanding is that Creative Commons NC just restricts *usage*[1] of the licensed files and does not affect the distribution of the files (or other files in the buildpack). Given that the Creative Commons NC files are not even used by the buildpack during its operation, it's not clear to me that there's an issue here. I'd recommend consulting an attorney.

Regardless, we have no plans to modify the affected upstream distributions of ruby that are included with the buildpack.

[1] https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

**Comment by andrew-edgar** [comment]
our legal team are still indicating having this file is a violation and we need some sort of remediation.  in theory this should be effecting the use of the ruby-buildpack by ANY commercial entry (IBM, SAP, VMWare etc).

The bad file is located in the ruby dependencies that are hosted on buildpacks.cloudfoundry.org.   Can this tea just replace the offending file in all the zips that are on buildpacks.cloudfoundry.org such as in this ...

https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.8-linux-x64-cflinuxfs3-7fa6c608.tgz

How are those tgz files created and stored?   Can we not fix those dependencies?

**Comment by andrew-edgar** [comment]
I also found this ...

https://github.com/ruby/did_you_mean/issues/107

Which seems to indicate that file would never be used at runtime and so would be safe to remove from the tgz that we host.

**Comment by luisapace** [comment]
Hi, I've consulted our Attorney and I insert here his explanation why we cannot have the file in the buildpack or in it’s dependencies:
"The yaml file is licensed under Creative Commons Attribution Non-Commercial Share Alike. Unlike other Creative Commons licenses, this license prevents a commercial entity from using the whole package because it contains this yaml file. Under the terms of the license, the mere existence of this file in the Ruby package prevents a commercial entity from using the package unless this file is removed and additionally the share alike terms of this license do not allow this yaml file to be licensed under more favorable terms."

**Comment by sclevine** [comment]
The gem contains the YAML file, but it isn't used for anything. It's just a left over artifact from development of the gem itself. The Creative Commons Attribution Non-Commercial Share Alike only appears to apply to "primary use"[1]. Can you check with your attorney to confirm that it's still a problem for you if the file isn't used?

In the meantime, @kvedurmu can you with with @martys34 to determine how much effort it would be for us to remove it from the older distributions of ruby?

[1] https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

**Comment by luisapace** [comment]
Hi, this is the legal position of our Attorney:

**_The Wiki page (https://wiki.creativecommons.org/wiki/NonCommercial_interpretation) has a disclaimer that says " THIS PAGE IS FOR INFORMATIONAL PURPOSES ONLY. CREATIVE COMMONS DOES NOT PROVIDE LEGAL ADVICE OR REPRESENTATION. CONSULT YOUR OWN LEGAL COUNSEL FOR LEGAL ADVICE. " Thus, this is not legal advice or guidance by the Creative Commons legal team. The interpretation by IBM Legal of the License is the mere existence of the file (whether it does anything or not) creates a problem as the whole work is licensed under the CC-BY-NC-SA. Under the definition of Licensed Material which means the artistic or literary work, database, or other material to which the Licensor applied this Public License, the CC-BY-NC-SA applies to the whole work. Further under the License Grant definition, the license applies to Material when it is produced or reproduced. Thus whenever the file is shared, it is considered to be reproduced._**

**Comment by martys34** [comment]
I believe we can remove this file from the tarball after building the binary and re-tar it. However, we'd request that you make a PR for this change.

There is a task in our [CI repo](https://github.com/cloudfoundry/buildpacks-ci) that builds the binary. We already manipulate the tarball after it is built in certain cases (e.g. [here](https://github.com/cloudfoundry/buildpacks-ci/blob/master/tasks/build-binary-new/builder.rb#L501-L505) where we [strip the top level directory off the tarball and re-tar it](https://github.com/cloudfoundry/buildpacks-ci/blob/master/tasks/build-binary-new/builder.rb#L401-L406)).

Something similar can be done as a special case for [ruby](https://github.com/cloudfoundry/buildpacks-ci/blob/master/tasks/build-binary-new/builder.rb#L624-L637).

**Comment by luisapace** [comment]
Hi, just an update, I've please asked Andrew to make the PR. Thanks to all of you

**Comment by andrew-edgar** [comment]
@martys34 I have submitted this PR https://github.com/cloudfoundry/buildpacks-ci/pull/67

Which should update the CI to remove the offending file. Please let me know how you want to test or update it and hopefully this will solve that issue.

**Comment by luisapace** [comment]
@martys34 Hi, our Attorney will be able to give us the green line to our code only when this problem will be solved, so currently we are blocked; may I kindly ask you:

1. what do you have in plan: release a new level of buildpack with safe ruby binaries OR "regenerate" the previous buildpacks including the safe ruby binaries?
2. could you please give us an estimation of the target date of that?

Thanks a lot.

**Comment by kvedurmu** [comment]
Hey @luisapace this PR is currently in our team's backlog of things to review. Once we get it merged, we will cut a new ruby buildpack version with this fix. I'd expect to have this in the next week or so.

**Comment by luisapace** [comment]
thanks for your quick reply!

**Comment by andrew-edgar** [comment]
I see the PR was merged 2 days ago.  When will the dependencies that are stored be updated?

Thanks

**Comment by kvedurmu** [comment]
Hey @andrew-edgar there are some pipeline issues on our end so I'd expect it to be another day or so before we get a buildpack update with this change.

If you see the latest changes on the develop branch to the [manifest](https://github.com/cloudfoundry/ruby-buildpack/blob/develop/manifest.yml) you can find a 2.5.8 ruby binary that has been re-built with this change. We're currently working on rebuilding the 2.5.7 binary.

**Comment by andrew-edgar** [comment]
I looked at 2.5.8 and it's pointing to a dependency that still has the wrong file in it.  so there must be something else to it as it's all part of the publishing of the dependencies.  Please let us know when the pipeline issues are worked out and if the dependencies are updated thanks.

as the new buildpack still references https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.7-linux-x64-cflinuxfs3-01b7d7a8.tgz. which still contains the old file that should be removed.

**Comment by kvedurmu** [comment]
@andrew-edgar just to clarify, the latest 2.5.8 dependency is https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_2.5.8_linux_x64_cflinuxfs3_738900ea.tgz. When I download it and run `tar tvf ruby_2.5.8_linux_x64_cflinuxfs3_738900ea.tgz | grep "incorrect_words"` I can see that the file has been removed. 

We're still working on rebuilding the 2.5.7 binary so i'll post an update when I have more to share.

**Comment by luisapace** [comment]
Hi, what about binaries for ruby 2.4.8 and 2.4.9? they have the same problematic file; are you going to rebuild them too or are you going to eliminate them at all from the buildpack? thanks for your support

**Comment by kvedurmu** [comment]
Ruby 2.4.X will be deprecated in the next release of the ruby buildpack. See - https://github.com/cloudfoundry/ruby-buildpack/issues/122

So, this problem only applies for 2.5.X binaries

**Comment by luisapace** [comment]
ok, thanks

**Comment by andrew-edgar** [comment]
when can we expect an updated build pack to be released as we would like to use the latest to remove the incorrectly licensed file.

**Comment by kvedurmu** [comment]
We just released Ruby Buildpack [1.8.17](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.17) which has re-built ruby 2.5.X binaries without the incorrect_words file. Please confirm that this looks good and we'll close the issue.

**Comment by kvedurmu** [comment]
Closing this issue. Thanks for reporting this and PRing in the change!
