### ISSUE TITLE
Ruby-buildpack-v1.8.17 still contains the file under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/ruby-buildpack#125]
Hi, 
I'm referring to CF Deployment 12.2 and ruby-buildpack-v1.8.17.

This ruby-buildpack-v1.8.17 still contain the the file "incorrect_words.yaml" under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License and that has been eliminated few days ago from ruby's binaries (at https://github.com/cloudfoundry/ruby-buildpack/issues/123).

I've found now this file in this new binary:

 jruby version: 9.2.11.1
  uri: https://buildpacks.cloudfoundry.org/dependencies/jruby/jruby_9.2.11.1-ruby-2.5_linux_x64_cflinuxfs3_f6e02bcf.tgz
  sha256: f6e02bcf02b7b33c48965b5c89adab4a2a9ebe20d345fd73d11cb4b1804df83f

in the paths:

- jruby_9.2.11.1-ruby-2.5_linux_x64_cflinuxfs3_f6e02bcf-0/lib/ruby/gems/shared/gems/did_you_mean-1.2.0/evaluation/incorrect_words.yaml
- jruby_9.2.11.1-ruby-2.5_linux_x64_cflinuxfs3_f6e02bcf-0/lib/target/classes/META-INF/jruby.home/lib/ruby/gems/shared/gems/did_you_mean-1.2.0/evaluation/incorrect_words.yaml
- jruby_9.2.11.1-ruby-2.5_linux_x64_cflinuxfs3_f6e02bcf-0/lib/target/jruby-stdlib-9.2.11.1.jar/META-INF/jruby.home/lib/ruby/gems/shared/gems/did_you_mean-1.2.0/evaluation/incorrect_words.yaml

I'm not sure that is not also in another binary coming from
https://github.com/cloudfoundry/ruby-buildpack/blob/v1.8.17/manifest.yml

I kindly ask you to manage to remove this file from all binaries in ruby-buildpack.

I'm fully available to give you other details.  Thanks

**Comment by andrew-edgar** [comment]
As with the last issue I'm doing a PR to remove this file in the buildpacks-ci repo.   

The PR is here https://github.com/cloudfoundry/buildpacks-ci/pull/68

**Comment by dumez-k** [comment]
PR reviewed and merged. Will build the new jruby binaries and update this thread when the build is successful.

**Comment by kvedurmu** [comment]
Hi @andrew-edgar @luisapace . We re-built jruby binaries using the PR. You can find the latest binaries on develop branch (https://github.com/cloudfoundry/ruby-buildpack/blob/develop/manifest.yml). However, it looks like this doesn't remove **all** references of that incorrect_words file. 
```
○ → wget -O jruby9.1.17 https://buildpacks.cloudfoundry.org/dependencies/jruby/jruby_9.1.17.0-ruby-2.3_linux_x64_cflinuxfs3_debfadeb.tgz
○ → tar tvf jruby9.1.17 | grep 'incorrect_words'
-rw-r--r--  0 root   root    23189 May  1 12:48 ./lib/target/rubygems/gems/did_you_mean-1.0.1/evaluation/incorrect_words.yaml
```

```
○ → wget -O jruby9.2.11 https://buildpacks.cloudfoundry.org/dependencies/jruby/jruby_9.2.11.1-ruby-2.5_linux_x64_cflinuxfs3_8d356264.tgz
○ → tar tvf jruby9.2.11 | grep 'incorrect_words'
-rw-r--r--  0 root   root    23339 May  1 12:47 ./lib/ruby/gems/shared/gems/did_you_mean-1.2.0/evaluation/incorrect_words.yaml
-rw-r--r--  0 root   root    23339 May  1 12:47 ./lib/target/classes/META-INF/jruby.home/lib/ruby/gems/shared/gems/did_you_mean-1.2.0/evaluation/incorrect_words.yaml
```

So, I'm thinking that that PR needs to be extended a little to delete from these file paths as well. Let us know what y'all think.

**Comment by luisapace** [comment]
@kvedurmu thanks for your work on it; yes, all the references have to be removed. Thanks

**Comment by luisapace** [comment]
@kvedurmu thanks for your work on it; yes, all the references should be removed for congruence and completeness, even if this module in 9.1.17 contains a version of incorrect_words.yaml without any reference to the bad license in its header; and this was the same for jruby 9.1.17 binary included in the previous version of ruby.buildpack, so the problem has not been evidenced in the past for jruby 9.1.17. Thanks

**Comment by kvedurmu** [comment]
We'd appreciate it if your team could PR in another change to remove the remaining references. Thanks

**Comment by andrew-edgar** [comment]
@kvedurmu I have created a NEW PR ... https://github.com/cloudfoundry/buildpacks-ci/pull/69

This one instead of picking certain paths to remove it just removes ALL references to the incorrect_words.yaml.

Hopefully this will improve things. :)

**Comment by luisapace** [comment]
@kvedurmu Hi, may I kindly ask you the planned date for the new ruby-buildpack ? It's urgent for me start working on it as soon as possible. Thanks

**Comment by kvedurmu** [comment]
@luisapace, apologies I didn't realize the latest PR was merged. I'll get something on our team's backlog to re-build the jruby binaries and reach back out once we get that done (hopefully sometime later this week).

**Comment by luisapace** [comment]
@kvedurmu yes, thanks, because I'm fully stucked on this :-(

**Comment by kvedurmu** [comment]
Hi @luisapace we just released https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.19 which has the re-compiled jruby binaries with the changes from the PR. I'm going to close this out, but feel free to open back up/file another issue if you notice any other problems.

**Comment by luisapace** [comment]
thanks!
