### ISSUE TITLE
Update node to 12.18?

### ISSUE THREAD

**Issue by frankieroberto** [cloudfoundry/ruby-buildpack#161]
Are there any plans for a release which bundles the latest LTS version of Node (12.18)?

**Comment by kvedurmu** [comment]
Hi. We only maintain a single version line of Node.js in the Ruby Buildpack (10.x). When Node 10.x goes EOS in April 2021, we will bump Node.js to the next LTS line (which will likely be 12.18). Closing this for now, but feel free to open back up if you have any questions.
