### ISSUE TITLE
Ruby 3.0.0 breaks test fixtures

### ISSUE THREAD

**Issue by thitch97** [cloudfoundry/ruby-buildpack#183]
Brats tests are failing due to the introduction of Ruby version 3.0.0. The brats_ruby fixture Gemfile.lock file needs to be updated to utilize different gem versions that work in cooperation with Ruby 3.0.0. We are not currently able to push thebrats_ruby app with an update Gemfile.lock. More investigation is needed to figure out what the problem is.
The error we see when we push the app is: 
`ERR /home/vcap/deps/0/vendor_bundle/ruby/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)`

Attached is the updated Gemfile.lock for the brats_ruby fixture with Ruby version 3.0.0 in the Gemfile. It took ages to get this, so putting it here for future. ([Gemfile.lock.txt](https://github.com/cloudfoundry/ruby-buildpack/files/5788029/Gemfile.lock.txt))

**Comment by Rylon** [comment]
Is Ruby 3 supported at all in the build pack? I don't see it as one of the versions.

**Comment by thitch97** [comment]
Hi @Rylon, we removed Ruby 3 temporarily due to compatibility issues we noticed during testing. The work to rectify this is ongoing and Ruby 3 support will be restored once those issues have been resolved.

**Comment by Rylon** [comment]
Hi @thitch97 thanks for the reply, I understand, good luck with the fixes.

**Comment by thitch97** [comment]
This issue has been resolved. Ruby 3.0.0 should be available with the next release of the buildpack.
