### ISSUE TITLE
IMPORTANT NOTICE: [ruby-buildpack] End of Support for ruby versions 2.5.x after 2021-04-23

### ISSUE THREAD

**Issue by kvedurmu** [cloudfoundry/ruby-buildpack#218]
The first release of the Ruby buildpack after 2021-04-23 will no longer include ruby versions 2.5.x. These ruby versions will no longer be supported upstream.[1] Please migrate your Ruby apps to supported versions of ruby before that time.

Note: Unless you are manually specifying a version of Ruby for the buildpack to use, or you have customized your Ruby buildpack, no action is required.

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel[2].

[1] - https://www.ruby-lang.org/en/downloads/branches/ 
[2] - https://cloudfoundry.slack.com/archives/C02HWMDUQ

**Comment by emmjohnson** [comment]
https://github.com/cloudfoundry/ruby-buildpack/commit/5934a351b84d68ed24f41c0b91fceed1b5f3c184

**Comment by fg-j** [comment]
A version of the buildpack has been released with ruby 2.5 removed https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.38
