### ISSUE TITLE
NOTICE: [ruby-buildpack] End of support for Node.js versions 10.x.x after 2021-05-27

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/ruby-buildpack#239]
The default version of Node.js in the Ruby buildpack will change from the latest 10.x.x version to the latest 14.x.x version in the first release of the Ruby buildpack after May 27, 2021. Due to the end of upstream support for Node.js 10.x.x, all buildpack users should ensure that their Ruby apps run on a minimum buildpack supported version of Node.js 14.x.x or later.

Additionally, the Ruby buildpack will temporarily include support for both Node.js versions 10.x.x and 14.x.x to allow Ruby applications to build on 14.x.x prior to the removal of support for Node.js 10.x.x.

For more information about Node.js 10.x or LTS timelines for 10.x, refer to: https://github.com/nodejs/Release
For more information about supported Node.js versions in the Ruby buildpack, refer to: https://buildpacks.cloudfoundry.org/#/buildpacks
 
Thanks,
Elliott Shanks, Buildpacks

**Comment by shanks3012** [comment]
For Buildpacks team - 

This issue requires that the Ruby buildpack add in support for Node.js 14.x in addition to the already supported Node.js 10.x.

**Comment by fg-j** [comment]
A version of the buildpack has been released adding node 14 https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.38
