### ISSUE TITLE
doesn't support version 2.2.0

### ISSUE THREAD

**Issue by lukaslehmann** [cloudfoundry/ruby-buildpack#28]
Hi Guys

Same as here with version 2.2.0;
https://github.com/cloudfoundry/ruby-buildpack/issues/8

Best regards
Lukas

**Comment by jchesterpivotal** [comment]
Thanks, Lukas. When we roll the next buildpack it'll be included as a matter of course.

I'm closing this issue here.

**Comment by lukaslehmann** [comment]
Thanks @jchesterpivotal !
