### ISSUE TITLE
README refers to bin/package which doesn't exist

### ISSUE THREAD

**Issue by nertzy** [cloudfoundry/ruby-buildpack#29]
The README talks about running bin/package and has a link to it, but that file doesn't exist.

**Comment by jchesterpivotal** [comment]
Thanks, @nertzy. Oversight on our part. We've also noted the same problem with the READMEs on 3 other buildpacks.

**Comment by jchesterpivotal** [comment]
I'll loop back and close this one when the README has been brought up to date.

**Comment by rvennam** [comment]
While the README is being updated, can you point us to a doc which outlines the correct procedure?

**Comment by squeedee** [comment]
```shell
cd <path to>/ruby-buildpack
GEMFILE=cf.Gemfile bundle install
GEMFILE=cf.Gemfile bundle exec buildpack-packager [online|offline]
```
This is from memory but I'm pretty sure it will work. The cf.Gemfile includes the buildpack-packager 'gem' (which is only a github repo)

**Comment by rvennam** [comment]
Thanks! I think you meant the env. var BUNDLE_GEMFILE instead of GEMFILE though:

BUNDLE_GEMFILE=cf.Gemfile bundle install
BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager [online|offline]

**Comment by jchesterpivotal** [comment]
We've updated the README, so I am going to close this issue.
