### ISSUE TITLE
 Ruby buildpacks do not work well with bundler >= 2.2.x

### ISSUE THREAD

**Issue by matobinder** [cloudfoundry/ruby-buildpack#301]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
    cf version 6.44.1+c3b20bfbe.2019-05-08
   "build": "2.7.33-build.38",
   "api_version": "2.139.0",
   "osbapi_version": "2.15",
```

What version of the buildpack you are using?
  `ruby_buildpack-cached-cflinuxfs3-v1.8.39.zip`

If you were attempting to accomplish a task, what was it you were attempting to do?
  `cf push`

What did you expect to happen?
To give this warning (invalid warning)

What was the actual behavior?
It gave this warning (which is false)
```
**WARNING** Removing `Gemfile.lock` because it was generated on Windows.
```

The bug is actually from this function in the repo
https://github.com/cloudfoundry/ruby-buildpack/blob/master/src/ruby/versions/ruby.go#L200

With bundler 2.2.x the PLATFORMS section no longer just says `ruby`
It looks like this
```
PLATFORMS
  x86_64-linux
```

So merely checking for `ruby` or `java` no longer suffices

**Comment by arjun024** [comment]
Fixed in v1.8.46
