### ISSUE TITLE
Update default runtime version?

### ISSUE THREAD

**Issue by rvennam** [cloudfoundry/ruby-buildpack#34]
Any plans to update default runtime version of Ruby to a later stable version (2.1.5 or 2.2.1)? 

https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/ruby.rb#L19

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question.

Yes, we're planning to include all latest versions of Ruby in an updated Ruby bulidpack. You can see our public backlog here: https://www.pivotaltracker.com/n/projects/1042066

Currently we're attempting to deal with the fact that, now that buildpacks support two stacks, the buildpacks have grown to an unwieldy size. As a result, we've been delayed a bit in shipping new buildpacks.

Within a few weeks we should be at the point where we'll be able to cut updated bulidpacks quickly once new interpreter versions are release. Thanks for your patience! I'll leave this issue open until we've shipped.

**Comment by rvennam** [comment]
Thanks. I understand that additional Ruby versions are being added to the buildpack. However, my question was regarding the default Ruby version chosen when no version is specified in the Gemfile. DEFAULT_RUBY_VERSION = "ruby-2.0.0"
https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/ruby.rb#L19

**Comment by rvennam** [comment]
Thanks for creating the story:
https://www.pivotaltracker.com/n/projects/1042066/stories/91706560

**Comment by flavorjones** [comment]
I've prioritized the story in our backlog; the next release should update the default Ruby version.
