### ISSUE TITLE
Update version of bundler in the buildpack

### ISSUE THREAD

**Issue by factorypreset** [cloudfoundry/ruby-buildpack#39]
The ruby-buildpack currently supplies version 1.7.12 of bundler. However the current version (as of today) is 1.10.5. The cloudfoundry ruby-buildpack should update to at least version 1.9.x.

It seems that some work was done earlier in the year to update to bundler 1.9. See:
https://www.pivotaltracker.com/n/projects/1042066/stories/90697228

At that time it was determined that the latest bundler supported upstream in the heroku buildpack was version 1.7.12. That's now changed, and Heroku supports 1.9.7. See:
https://devcenter.heroku.com/articles/ruby-support#libraries

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question.

As of ruby-buildpack v1.4.2, we're shipping bundler 1.9.7. You can always see what we're shipping by looking at the `manifest.yml` in a core buildpack:

> https://github.com/cloudfoundry/ruby-buildpack/blob/master/manifest.yml#L43

Is it possible that you're using an older version of the buildpack? It looks like v1.2.1 updated to Bundler 1.7, so I'm guessing you're running somewhere in the range of v1.2.1..v1.4.2.

**Comment by factorypreset** [comment]
Hi @flavorjones -- thanks, you're right! -- it turns out I do indeed have v1.3.0. Do you happen to know what cf-release included the update to ruby-buildpack v1.4.2+? (from the timing it seems like it might have been cf-release 208).

**Comment by flavorjones** [comment]
@factorypreset The commit putting ruby-buildpack v1.4.2 on cf-release was eead0a0ce88de7a46cb8854ea6caca61b95e3024, which first appeared in v211.
