### ISSUE TITLE
Update buildpack so it doesn't remove config/database.yml

### ISSUE THREAD

**Issue by zidekmat** [cloudfoundry/ruby-buildpack#42]
Replacing database.yml is not really necessary because now you can't specify the schema you want to use. For example if you want to use blue/green zero downtime deployment with database supporting multiple schemas, then it's not even possible. When you deploy blue it's using schema 'user1' and deploying green makes it use another schema 'user2' so you would need to move all data between schemas.
Heroku already removed this function [here](https://devcenter.heroku.com/changelog-items/426) and [here](https://discussion.heroku.com/t/rails-4-1-database-yml-no-longer-overwritten-on-heroku/550).
Can you also implement this functionality?

**Comment by jtarchie** [comment]
@zidekmat the buildpack pulls from upstream of Heroku's Ruby buildpack. The issues that you point to are actually [already merged](https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/rails41.rb#L18) in. For anything Rails 4.1 and above, a `database.yml` does not get generated.

**Comment by zidekmat** [comment]
I'm sorry, I didn't notice it's for Rails 4.1+. Thanks :)
