### ISSUE TITLE
BuildpackCompileFailed when running curl for bundler

### ISSUE THREAD

**Issue by gudatcomputers** [cloudfoundry/ruby-buildpack#43]
Trying to use buildpack v1.4.2 and logs show that getting bundler from s3 fails. 

Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '4d1038d2d7b23ec303491db4fba80faf8651a90d'
-------> Buildpack version 1.4.2
 !
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 10 --max-time 90 https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly:
 !
 !     gzip: stdin: unexpected end of file
 !     tar: Child returned status 1
 !     tar: Exiting with failure status due to previous errors
 !
/tmp/buildpacks/ruby-buildpack/lib/language_pack/shell_helpers.rb:50:in `run!': Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 10 --max-time 90 https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
gzip: stdin: unexpected end of file
tar: Child returned status 1

Our network admins state that amazon S3 is resetting TCP connections and that seems to be why curl is failing.

**Comment by jtarchie** [comment]
@gudatcomputers we are unable to recreate this issue. I don't know what is causing the resetting of TCP connections. I've tried on two different networks in NYC and SF with no problems. Could it be your network?

To prevent problems like this, we highly recommend using the cached buildpack that can be downloaded from the [github releases](https://github.com/cloudfoundry/ruby-buildpack/releases). This version of the buildpack comes with the dependencies vendor, so it doesn't require a network connection.

**Comment by gudatcomputers** [comment]
@jtarchie I assume it is a problem with our network.  We ended up downloading the cached buildpack.
