### ISSUE TITLE
Cloud Foundry ruby buildpack points to heroku docs

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry/ruby-buildpack#44]
Every time I push a ruby based app I get the following warning which points to Heroku docs. Do we not have our own set of docs which explain the warning?

```
###### WARNING:
       No Procfile detected, using the default web server (webrick)
       https://devcenter.heroku.com/articles/ruby-default-web-server
```

**Comment by Dannyzen** [comment]
Hey @roxtar since we are upstream from Heroku we also inherent their error messaging. 
If this does not answer your question please re-open this issue.
