### ISSUE TITLE
How to make ruby-buildpack work behind the proxy？

### ISSUE THREAD

**Issue by IkuEisou** [cloudfoundry/ruby-buildpack#46]
I deployed a CF on a PC with cf_nise_installer, and push a sample app that comes from "https://github.com/yudai/cf_nise_installer/tree/master/test_app".
When starting the app, there is a error as following.
Starting app hello in org DevBox / space sp1 as admin...
-----> Downloaded app package (1.4M)
-------> Buildpack version 1.6.7
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.2.3
-----> Installing dependencies using 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching source index from http://rubygems.org/
       Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
       Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
       Could not fetch specs from http://rubygems.org/
       Bundler Output: Fetching source index from http://rubygems.org/
       Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
       Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
       Could not fetch specs from http://rubygems.org/
 !
 !     Failed to install gems via Bundler.
 !
Staging failed: Buildpack compilation step failed

If run the "bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment" on the PC that is the host of the CF, it's OK.

So, it seems that the proxy that setted on the host doesn't work on the ruby-buildpack.
If it was right , cloud you tell me how to set up the proxy on the ruby-buildpack?

**Comment by jtarchie** [comment]
@IkuEisou the ruby buildpack uses `curl` for all its HTTP processing.

If you set the environment variable `http_proxy`, then `curl` should pick it up. You can do that with either your `manifest.yml` or with `cf set-env`.

Let us know if that works for you.

**Comment by IkuEisou** [comment]
Thank you for your reply.
I has set up environment variable  http_proxy and manifest.yml for sample app as follow.
############################################################
$ cf env hello
Getting env variables for app hello in org DevBox / space sp1 as admin...
OK

System-Provided:
{
 "VCAP_APPLICATION": {
  "application_id": "0679d8c2-e0c9-4f34-9a5e-d105cbe90f5d",
  "application_name": "hello",
  "application_uris": [
   "hello.10.167.227.48.xip.io"
  ],
  "application_version": "4691ead6-1ffd-4739-a021-ae43eadd2753",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 256
  },
  "name": "hello",
  "space_id": "2d4b7770-aad9-404b-a906-5777302aa911",
  "space_name": "sp1",
  "uris": [
   "hello.10.167.227.48.xip.io"
  ],
  "users": null,
  "version": "4691ead6-1ffd-4739-a021-ae43eadd2753"
 }
}

User-Provided:
HTTPS_PROXY: http://10.167.227.38:1080
HTTP_PROXY: http://10.167.227.38:1080
no_proxy: 127.0.0.1,api.10.167.227.48.xip.io,doppler.10.167.227.48.xip.io,hm9000.10.167.227.48.xip.io,uaa.10.167.227.48.xip.io,loggregator.10.167.227.48.xip.io,hello.10.167.227.48.xip.io

Running Environment Variable Groups:
HTTP_PROXY: http://10.167.227.38:1080

Staging Environment Variable Groups:
HTTP_PROXY: http://10.167.227.38:1080
############################################################

But it doesn't work.
If run the "bundle install " on the PC that is the host of the CF, it's OK.
So, it meas that there are no problem at the proxy and the rubygems source.

Cloud you tell me how to find out the cause of the "Bundler::HTTPError " ?

**Comment by jtarchie** [comment]
@IkuEisou, are you sure that the container has access to the proxy? There maybe a security group setup on the staging of the application -- `cf staging-security-groups` and then to see the specific rules `cf security-group <name>`. It could be blocking the proxy server from within the container.

You can also prepackage all your rubygems with your application, so when you push it up `bundle` does it have to reach out to the internet at all, these are the [instructions](https://github.com/cloudfoundry/ruby-buildpack#vendoring-app-dependencies).

**Comment by IkuEisou** [comment]
I prepackage all of the rubygems with the app, and it works.Thank you very much.

I found that the DEA container can't access to the proxy.So I  tried to bind the public_networks and dns security group with my CF deployment, but it doesn't work.

My security group setup on the  staging of the application as following.
###############################################################
$ cf staging-security-groups
Acquiring staging security group as admin
OK

public_networks
dns

$ cf security-group public_networks
Getting info for security group public_networks as admin
OK
Name    public_networks
Rules
        [
                {
                        "destination": "0.0.0.0-9.255.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "11.0.0.0-169.253.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "169.255.0.0-172.15.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "172.32.0.0-192.167.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "192.169.0.0-255.255.255.255",
                        "protocol": "all"
                }
        ]
No spaces assigned

$ cf security-group dns
Getting info for security group dns as admin
OK
Name    dns
Rules
        [
                {
                        "destination": "0.0.0.0/0",
                        "ports": "53",
                        "protocol": "tcp"
                },
                {
                        "destination": "0.0.0.0/0",
                        "ports": "53",
                        "protocol": "udp"
                }
        ]
No spaces assigned

$ cf security-group private_networks
Getting info for security group private_networks as admin
OK

Name    private_networks
Rules
        [
                {
                        "destination": "10.0.0.0-10.255.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "172.16.0.0-172.31.255.255",
                        "protocol": "all"
                },
                {
                        "destination": "192.168.0.0-192.168.255.255",
                        "protocol": "all"
                }
        ]

No spaces assigned
###############################################################

The IP of the proxy is  10.167.227.38/255.255.255.0 that is the same as the network of CF host.
If the setup of the security group was wrong, how to fix it?

**Comment by jtarchie** [comment]
@IkuEisou it looks like you might need to add your `private_networks` security-group to `staging-security-groups` to allow communication in that IP address range.

I'm going to close this issue, though, as this is not a buildpack related issue. If you have more questions about security groups and CF setup, please ask in the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/).
