### ISSUE TITLE
use rubygems mirror for bundle install

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry/ruby-buildpack#48]
Is it possible to rebuild the buildpack so the default location to install ruby gems from is not rubygems.org. At my company we do not have internet access for installing gems when deploying apps. I know it is possible to use a cached version of the buildpack and have the app vendor its dependencies, but we have an internal mirror of rubygems.org. Is there a setting that can be changed to allow for this mirror  to be used instead?

**Comment by davidjahn** [comment]
Hi @warroyo , this should be as simple as running:

```
bundle config --local mirror.https://rubygems.org https://my-internal-rubygem-mirror
cf push
```

You can then commit the ".bundle" directory to your app's codebase to ensure the behavior happens for every future `cf push`. Let me know if this solves your problem!

Best
David

**Comment by warroyo** [comment]
thank you @davidjahn I will give this a try

**Comment by flavorjones** [comment]
@warroyo Our recommended practice is to vendor all your rubygems into your application, so that there's no need to download gems during application staging.

You can do this by running

```
bundle package --all
```

before `cf push`ing.

**Comment by warroyo** [comment]
thank you, this is working for me .
