### ISSUE TITLE
Profile warning seems misleading

### ISSUE THREAD

**Issue by LukeWinikates** [cloudfoundry/ruby-buildpack#50]
When pushing a Ruby app that specifies a `command` in the manifest.yml like this:

```
  command: bundle exec rake db:migrate && bundle exec rails s thin -p $PORT
```

I see this warning:

```
###### WARNING:
       No Procfile detected, using the default web server (webrick)
```

But then later, I see 

```
2016-02-05T12:27:15.26-0800 [CELL/0]     OUT Starting health monitoring of container
2016-02-05T12:27:20.33-0800 [APP/0]      OUT => Booting Thin
2016-02-05T12:27:20.33-0800 [APP/0]      OUT => Rails 4.2.5.1 application starting in production on http://0.0.0.0:8080
2016-02-05T12:27:20.33-0800 [APP/0]      OUT => Run `rails server -h` for more startup options
2016-02-05T12:27:20.33-0800 [APP/0]      OUT => Ctrl-C to shutdown server

```

So clearly CF is using Thin, presumably because it's in the command. It's not using Webrick, so the Procfile warning isn't accurate, at least on PWS.

**Comment by flavorjones** [comment]
Right, this is because of this code, which we've inherited from the upstream Heroku ruby buildpack:

> https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/base.rb#L107-L111

We may want to consider omitting this message if the application has declared a start command.

**Comment by RochesterinNYC** [comment]
Thanks for bringing this to our attention @LukeWinikates. We've decided to remove that warning

```
###### WARNING:
       No Procfile detected, using the default web server (webrick)
       https://devcenter.heroku.com/articles/ruby-default-web-server
```

completely as it's fairly non-CF specific and both Diego and DEA will output in the logs what command was used to start your app.

This change is reflected in the following [commit](https://github.com/cloudfoundry/ruby-buildpack/commit/c7168a0f5ff0ff26fe3bc6feeeed1d79f05418b6) on the develop branch. It should be out in the next ruby buildpack release. Thanks!
