### ISSUE TITLE
Update bundler version in the ruby-buildpack

### ISSUE THREAD

**Issue by JasmoMyer** [cloudfoundry/ruby-buildpack#52]
Hello there,

The current version of bundler shipping with the cloudfoundry ruby-buildpack is 1.9.7 (from what I can see in the manifest.yml)

I wonder if bundler could be updated to the latest non-pre-release, 1.11.2 (https://github.com/bundler/bundler/blob/master/CHANGELOG.md)

That would be awesome.

Thanks!

**Comment by flavorjones** [comment]
I'd like to vote in favor of this change as well.

I know we have our "ruby wildcard" PR coming in 1.12, and so understand if you want to wait for that, too.

**Comment by Dannyzen** [comment]
Thanks for the feedback @JasmoMyer. @flavorjones and I were informed today that Bundler 1.12 is due to be released in the very near future. We'll be sure to respond with a new ruby buildpack including it then.

**Comment by Dannyzen** [comment]
Hey @JasmoMyer a friendly heads up that we decided to include 1.11.2 in the most recent release: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.6.14. Thanks for voicing your opinion earlier.

**Comment by JasmoMyer** [comment]
Wonderful! Thanks for your help!
