### ISSUE TITLE
RFC: Change Node.js version from v0.12 to v4

### ISSUE THREAD

**Issue by davidjahn** [cloudfoundry/ruby-buildpack#53]
Hi,

The Ruby buildpack currently provides users access to Node by packaging it with Ruby apps pushed on Cloud Foundry. As discussed in the [related issue](https://github.com/cloudfoundry/nodejs-buildpack/issues/50) for the Node.js buildpack, since April 2016 [1] Node.js v0.12 will only be supported in a maintenance capacity.

To provide users with a longer active LTS schedule, we are proposing to change the Node version in the Ruby buildpack from v0.12 to v4.

We are planning to move forward on this issue by 4/25/2016. If you have any concerns or feedback please comment on this issue.

[1] - https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png

**Comment by Dannyzen** [comment]
This has been committed to develop and will be in the [upcoming release](https://www.pivotaltracker.com/story/show/119085693) of the Ruby Buildpack
