### ISSUE TITLE
RFC: Updating the default version of Ruby to 2.3.x

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/ruby-buildpack#54]
Hi all,

We'd like to let you know that in the next week we'll be scheduling work to update the default version of Ruby in the Ruby Buildpack from 2.2.x to 2.3.x. This change only affects application that don't specify the version of Ruby in the Gemfile.

Please let us know if this is an undesired change either by commenting on this issue or replying to [this thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/MLESLZOLFPKRNQB2NUHJQ66WBWLSLFGU/). Also, please keep in mind that you can always force the buildpack to use a specific version of ruby by adding the following line to your `Gemfile`:

```
ruby "2.2.4"
```

**Comment by flavorjones** [comment]
+1 This seems reasonable to me.

**Comment by Dannyzen** [comment]
This has been committed to develop and will be in the [upcoming release](https://www.pivotaltracker.com/story/show/119085693) of the Ruby buildpack

**Comment by jvshahid** [comment]
@Dannyzen should we close this issue given that the work is already done ?

**Comment by Dannyzen** [comment]
:ship:
