### ISSUE TITLE
Buildpack fails when Gemfile contains environment vars

### ISSUE THREAD

**Issue by avellable** [cloudfoundry/ruby-buildpack#56]
What version of Cloud Foundry are you using?

```
$ cf -v
cf version 6.14.1+dc6adf6-2015-12-22
```

What version of the buildpack you are using?
latest viz. 1.6.18

If you were attempting to accomplish a task, what was it you were attempting to do?
Starting a pushed app.

What was the actual behavior?

```
-----> Compiling Ruby/Rails
...
!
 !     uninitialized constant LanguagePack::RubySemverVersion::GemfileReader::RUBY_PLATFORM
 !
./Gemfile:6:in `ruby_requirement': uninitialized constant LanguagePack::RubySemverVersion::GemfileReader::RUBY_PLATFORM (NameError)
```

My Gemfile contains:

```
gem 'thin' unless RUBY_PLATFORM =~ /mingw|mswin/i
```

**Comment by geramirez** [comment]
FYI, we'll be working on a solution for this issue this week.

**Comment by RochesterinNYC** [comment]
This has been addressed by https://github.com/cloudfoundry/ruby-buildpack/commit/6f0f13ffbd6e15717afcbf108250e5051b9f179c on develop. It will be available in the next ruby buildpack release.
