### ISSUE TITLE
Vanilla Ruby app requires version 4.1.0.beta1 or lower of ActiveRecord

### ISSUE THREAD

**Issue by azzamallow** [cloudfoundry/ruby-buildpack#59]
What version of Cloud Foundry are you using?
```
{
   "name": "vcap",
   "build": "2222",
   "version": 2,
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.25.0",
}
```

**What version of the buildpack you are using?** v1.6.18

**If you were attempting to accomplish a task, what was it you were attempting to do?**
Deploy a ruby worker app with a database configured

**What did you expect to happen?**
The application to be able to talk to the database via DATABASE_URL

**What was the actual behavior?**
The buildpack did not rebuild the database.yml file, hence there was no configuration to talk to the production database

---

I have these lines of code in my app to connect to the database:
```
environment = ENV['RACK_ENV'] || 'development'
database_config = YAML::load(File.open('config/database.yml'))
ActiveRecord::Base.establish_connection(database_config[environment])
```

With RACK_ENV at production, I get the following error:
```
ActiveRecord::AdapterNotSpecified: 'production' database is not configured. Available: []
```

Looking at the code in the buildpack, I found [this](https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/language_pack/ruby.rb#L677):
```
return false if  bundler.has_gem?('activerecord') && bundler.gem_version('activerecord') >= Gem::Version.new('4.1.0.beta1')
```

To workaround the problem I have downgraded activerecord to 4.0.13. The problem has gone away however I am stuck using an older version of activerecord. I do not know why the limitation on the activerecord version is there.

**Comment by RochesterinNYC** [comment]
The heroku ruby buildpack, which our CF buildpack is downstream from, will not create `database.yml` files for `activerecord` 4.1. It will instead use the `DATABASE_URL` environment variable in connecting to the database. We suggest you use this environment variable as well.

Heroku context:
heroku/heroku-buildpack-ruby#403
heroku/heroku-buildpack-ruby#364

Out of curiosity, is this a Ruby app that uses activerecord but not rails?

**Comment by azzamallow** [comment]
Thanks for the clarification.

Yes it's a worker app, so there is web application layer such as rails or Sinatra involved.
