### ISSUE TITLE
Cannot set ActiveRecord connection pool size with database.yml in Rails4.1+/ruby_buildpack

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/ruby-buildpack#62]
**What version of Cloud Foundry are you using?**
`API version: 2.59.0
`

**What version of the buildpack you are using?**
`
ruby_buildpack-cached-v1.6.21.zip
`

**If you were attempting to accomplish a task, what was it you were attempting to do?**
Override the default ActiveRecord connection pool size 5 with higher value 15

**What did you expect to happen?**
ActiveRecord connection pool size should be set to 15 successfully

**What was the actual behavior?**
ActiveRecord connection pool size is still 5

**Please confirm where necessary:**
**This issue can be reproduced with cloud foundry sample [pong_matcher_rails](https://github.com/cloudfoundry-samples/pong_matcher_rails)
ActiveRecord connection pool size is set to 15 in config/database.yml.**
`
Daivd-Office-Mac:pong_matcher_rails-master ubuntu$ more config/database.yml `
`default: &default`
 ` adapter: mysql2`
 ` encoding: utf8`
 ` pool: 15`
`  username: root`
 ` password:`
 ` port: 3306`
 ` host: localhost`
``
`development:`
`  <<: *default`
`  database: pong_matcher_rails_development`
``
`test:`
`  <<: *default`
`  database: pong_matcher_rails_test`
`Daivd-Office-Mac:pong_matcher_rails-master ubuntu$ `

**Cf push run successfully.**
`Daivd-Office-Mac:pong_matcher_rails-master ubuntu$ cf push -n mysubdomain-david  `
`Using manifest file /Users/david/Downloads/pong_matcher_rails-master/manifest.yml`
``
`Updating app railspong in org gss-apj / space David as dzhou@pivotal.io...`
`OK                                                                        `
``
`Using route mysubdomain-david.cfapps.io                                                    `
`Uploading railspong...                                                                     `
`Uploading app files from: /Users/david/Downloads/pong_matcher_rails-master                 `
`Uploading 45K, 102 files                                                                   `
`Done uploading                                                                             `
`OK                                                                                         `
`Binding service mysql to app railspong in org gss-apj / space David as dzhou@pivotal.io... `
`OK                                                                                         `                                                                                         
`Stopping app railspong in org gss-apj / space David as dzhou@pivotal.io...                 `
`OK                                                                                         `
`Starting app railspong in org gss-apj / space David as dzhou@pivotal.io...                 `
`Downloading binary_buildpack...                                                            `
`Downloading nodejs_buildpack...                                                            `
`Downloading java_buildpack...                                                              `
`Downloading staticfile_buildpack...                                                        `
`Downloading ruby_buildpack...                                                              `
`Downloaded java_buildpack                                                                  `
`Downloaded staticfile_buildpack                                                            `
`Downloading go_buildpack...                                                                `
`Downloading python_buildpack...                                                            `
`Downloaded nodejs_buildpack                                                                `
`Downloading php_buildpack...                                                               `
`Downloaded binary_buildpack                                                                `
`Downloading liberty_buildpack...                                                           `
`Downloaded ruby_buildpack                                                                  `
`Downloaded python_buildpack                                                                `
`Downloaded go_buildpack                                                                    `
`Downloaded liberty_buildpack                                                               `
`Downloaded php_buildpack                                                                   `
`Creating container                                                                         `
`Successfully created container                                                             `
`Downloading app package...                                                                 `
`Downloaded app package (27.5K)                                                             `
`Downloading build artifacts cache...                                                       `
`Downloaded build artifacts cache (12.8M)                                                   `
`Staging...                                                                                 `
`-------> Buildpack version 1.6.21                                                          `
`       Downloaded [file:///tmp/buildpacks/52950f43493e01421589bf265ae8c07e/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_bundler_bundler-1.12.5.tgz]     `
`-----> Compiling Ruby/Rails                                                                                                                                                    `
`       Downloaded [file:///tmp/buildpacks/52950f43493e01421589bf265ae8c07e/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_ruby_ruby-2.3.1-linux-x64.tgz]  `
`-----> Using Ruby version: ruby-2.3.1                                                                                                                                          `
`-----> Installing dependencies using bundler 1.12.5                                                                                                                            `
`       Downloaded [file:///tmp/buildpacks/52950f43493e01421589bf265ae8c07e/dependencies/https___buildpacks.cloudfoundry.org_ruby_binaries_cflinuxfs2_libyaml-0.1.6.tgz]        `
`       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment                                                   `
`       Using i18n 0.7.0                                                                                                                                                        `
`       Using rake 10.4.2                                                                                                                                                       `
`       Using json 1.8.3                                                                                                                                                        `
`       Using minitest 5.7.0                                                                                                                                                    `
`       Using thread_safe 0.3.5                                                                                                                                                 `
`       Using builder 3.2.2                                                                                                                                                     `
`       Using erubis 2.7.0                                                                                                                                                      `
`       Using rack 1.5.5                                                                                                                                                        `
`       Using mime-types 2.6.1                                                                                                                                                  `
`       Using arel 5.0.1.20140414130214                                                                                                                                         `
`       Using kgio 2.9.3                                                                                                                                                        `
`       Using mysql2 0.3.18                                                                                                                                                     `
`       Using bundler 1.12.5                                                                                                                                                    `
`       Using thor 0.19.1                                                                                                                                                       `
`       Using rails_serve_static_assets 0.0.4                                                                                                                                   `
`       Using rails_stdout_logging 0.0.3                                                                                                                                        `
`       Using raindrops 0.14.0                                                                                                                                                  `
`       Using tzinfo 1.2.2                                                                                                                                                      `
`       Using mail 2.6.3                                                                                                                                                        `
`       Using rack-test 0.6.3                                                                                                                                                   `
`       Using sprockets 3.2.0                                                                                                                                                   `
`       Using rails_12factor 0.0.3                                                                                                                                              `
`       Using activesupport 4.1.8                                                                                                                                               `
`       Using unicorn 4.9.0                                                                                                                                                     `
`       Using actionview 4.1.8                                                                                                                                                  `
`       Using activemodel 4.1.8                                                                                                                                                 `
`       Using actionpack 4.1.8                                                                                                                                                  `
`       Using activerecord 4.1.8                                                                                                                                                `
`       Using actionmailer 4.1.8                                                                                                                                                `
`       Using railties 4.1.8                                                                                                                                                    `
`       Using sprockets-rails 2.3.2                                                                                                                                             `
`       Using rails 4.1.8                                                                                                                                                       `
`       Bundle complete! 5 Gemfile dependencies, 32 gems now installed.                  `
`       Gems in the groups development and test were not installed.                      `
`       Bundled gems are installed into ./vendor/bundle.                                 `
`       Bundle completed (0.35s)                                                         `
`       Cleaning up the bundler cache.                                                   `
`-----> Preparing app for Rails asset pipeline                                           `
`       Running: rake assets:precompile                                                  `
`       Asset precompilation completed (1.19s)                                           `
`       Cleaning assets                                                                  `
`       Running: rake assets:clean                                                       `
`###### WARNING:                                                                         `
`       You have not declared a Ruby version in your Gemfile.                            `
`       To set your Ruby version add this line to your Gemfile:                          `
`       ruby '2.3.1'                                                                     `
`       # See https://devcenter.heroku.com/articles/ruby-versions for more information.  `
`Exit status 0                                                                           `
`Staging complete                                                                        `
`Uploading droplet, build artifacts cache...                                             `
`Uploading build artifacts cache...                                                      `
`Uploading droplet...                                                                    `
`Uploaded build artifacts cache (12.8M)                                                  `
`Uploaded droplet (24.5M)                                                                `
`Uploading complete                                                                      `
`Destroying container                                                                    `
`Successfully destroyed container                                                        `
`                                                                                        `
`1 of 1 instances running                                                                `
`App started                                                                             `                                                                                        
`OK                                                                                      `
`App railspong was started using this command bin/rake cf:on_first_instance db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb`
`Showing health and status for app railspong in org gss-apj / space David as dzhou@pivotal.io...     `
`OK                                                                                                  `
`requested state: started                                                                            `
`instances: 1/1                                                                                      `
`usage: 256M x 1 instances                                                                           `
`urls: mysubdomain-david.cfapps.io                                                                   `
`last uploaded: Fri Aug 19 07:19:13 UTC 2016                                                         `
`stack: cflinuxfs2                                                                                   `
`buildpack: ruby 1.6.21                                                                              `
`                                                                                                    `
`     state     since                    cpu    memory          disk           details               `
`#0   running   2016-08-19 03:19:53 PM   0.0%   65.1M of 256M   104.4M of 1G                         `
                                                                                                     
**However ActiveRecord connection pool size is still 5.**
`vcap@qtnnq0qgbuu:~$ rails c`
`Loading production environment (Rails 4.1.8)`
`irb(main):001:0> ActiveRecord::Base.connection_pool.instance_eval { @size } `
`=> 5`
`irb(main):002:0> `

**Comment by RochesterinNYC** [comment]
If you `cf ssh` into your running app, and take a look at the `config/database.yml` file, has it been rewritten or does it match the `config/database.yml` contents on your local machine?

**Comment by David-Pivotal** [comment]
Hi Rochester,

It matches the config/database.yml on my local machine.

`Daivd-Office-Mac:pong_matcher_rails-master ubuntu$ cf ssh railspong`
`vcap@qtnnq0qgbuu:~$ cd app                                         `
`vcap@qtnnq0qgbuu:~/app$ more config/database.yml                   `
`default: &default                                                  `
`  adapter: mysql2                                                  `
`  encoding: utf8                                                   `
`  pool: 15                                                         `
`  username: root                                                   `
`  password:                                                        `
`  port: 3306                                                       `
`  host: localhost                                                  `
`                                                                   `
`development:                                                       `
`  <<: *default                                                     `
`  database: pong_matcher_rails_development                         `
`                                                                   `
`test:                                                              `
`  <<: *default                                                     `
`  database: pong_matcher_rails_test                                `
`vcap@qtnnq0qgbuu:~/app$                                            `

**Comment by RochesterinNYC** [comment]
Hi @David-Pivotal, we tried this out with a [rails 4 fixture app](https://github.com/cloudfoundry/ruby-buildpack/tree/pool-connection-15/cf_spec/fixtures/rails4_web_app) that uses mysql2 and a connection pool of 15. We were unable to reproduce your issue's behavior.

Our steps:
In local environment:
```
git clone git@github.com:cloudfoundry/ruby-buildpack.git
git checkout pool-connection-15
cd cf_spec/fixtures/rails4_web_app
cf push rails4
```

Inside SSH session:
```
cf ssh rails4
cd app
export HOME=$(pwd)
source .profile.d/ruby.sh
rails c
```
In the rails console while inside the ssh session:
```
Loading production environment (Rails 4.1.8)
irb(main):001:0> ActiveRecord::Base.connection_pool.instance_eval { @size }
=> 15
```

**Comment by David-Pivotal** [comment]
Hi Rochester,

Thanks for your help. It is really helpful. I will check and get back to you soon.

**Comment by David-Pivotal** [comment]
Hi Rochester,

I am able to set connection pool size to 15. Please feel free to close this issue.
Thank you for your help!
