### ISSUE TITLE
jq in the buildpack

### ISSUE THREAD

**Issue by farahfa** [cloudfoundry/ruby-buildpack#68]
Is there a way to support jq (kinda like the go-buildpack) in this ruby-buildpack? Because it'd be helpful to have it there so one could use the ruby-jq gem (which needs jq in order to compile).

**Comment by sclevine** [comment]
jq 1.3 is provided by the cflinuxfs2 rootfs, is that sufficient?

**Comment by farahfa** [comment]
Hmm, all our apps are installed on cflinuxfs2 derivatives.. I wonder why I still get that error.. Has this always been the case or was JQ added in a certain version of cflinuxfs2?

**Comment by RochesterinNYC** [comment]
`jq` has been in the cflinuxfs2 rootfs since July 29th, 2015: https://github.com/cloudfoundry/stacks/commit/8770b5185656938c943ee9bb2a5892097d055264

**Comment by sesmith177** [comment]
Closing since jq is in the cflinuxfs2 rootfs
