### ISSUE TITLE
Release: ruby-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/ruby-buildpack#727]
Release reminder for ruby-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/ruby-buildpack/compare/v1.9.2..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/ruby-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by sophiewigmore** [comment]
https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.9.3
