### ISSUE TITLE
Support for New Relic APM

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry/ruby-buildpack#73]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`? 1.9

What version of the buildpack you are using? current

If you were attempting to accomplish a task, what was it you were attempting to do? attempted to integrate New Relic APM via pivotal docs (https://docs.run.pivotal.io/marketplace/services/newrelic/#ruby) but was unable to get data streamed to New Relic. There wasn't any error but also no logs.

What did you expect to happen? was expecting metrics being offloaded by the new relic rpm (installed via Gemfile and config/newrelic.yml)

github repo located at (https://docs.run.pivotal.io/marketplace/services/newrelic/#ruby --- step #2) talks of using this as an example to connect with NR APM.

What was the actual behavior? none

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Thanks for the report! I prioritized the above story to address this.

**Comment by sclevine** [comment]
@phopper-pivotal We found that the instructions on that page are correct, but the sample app was out of date and confusing. The sample app was removed from that documentation.

**Comment by phopper-pivotal** [comment]
thanks sclevine. after sometime, and with debug enabled, I was able to grab the collector endpoint and view dashboard in NR.

of side note and not for this forum, was hoping the NR service broker to do this heavy lifting much like it does for Java.
