### ISSUE TITLE
Rails 5.0 webpacker:compile failed

### ISSUE THREAD

**Issue by yohfee** [cloudfoundry/ruby-buildpack#85]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.29.0+ff886fa93.2017-07-24

What version of the buildpack you are using?
Buildpack version 1.6.46

If you were attempting to accomplish a task, what was it you were attempting to do?
`rails webpacker:compile`
ruby 2.4.1
rails 5.0.5
webpacker 2.0

What did you expect to happen?
Precompiling assets succeed.

What was the actual behavior?
Precompiling assets failed.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction
```
OUT        yarn install v0.27.5
OUT        warning package.json: No license field
OUT        warning No license field
OUT        [1/4] Resolving packages...
OUT        [2/4] Fetching packages...
OUT        error postcss-smart-import@0.7.5: The engine "node" is incompatible with this module. Expected version ">=6.0.0".
OUT        error Found incompatible module
OUT        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
OUT  !
OUT  !     Precompiling assets failed.
OUT  !
```

Below shows node 6 is available only rails 5.1+. How can I use node 6 with rails 5.0?
https://github.com/rakutentech/ruby-buildpack/blob/master/lib/language_pack/helpers/node_installer.rb#L36-L40

**Comment by sclevine** [comment]
We plan to support providing custom versions of Node.js via the Node.js buildpack when multiple buildpack support is complete. Currently, we only provide the active LTS version of Node.js that was available when the rails version line was first released.

If it's difficult to work around this before multiple buildpack support is available, we could introduce an environment variable to force specific node versions. @dgodd, does this seem reasonable?

**Comment by yohfee** [comment]
I see, thanks. I'll push the local compiled assets for now.

**Comment by dgodd** [comment]
@sclevine I'm in favor of the environment variable plan

**Comment by sclevine** [comment]
Given that multiple buildpack support is available in the latest CAPI release, I'd like to wait on this until we know if it's necessary. In the long term, we should deprecate the provided Node.js anyways.

**Comment by jainankita90** [comment]
Looking forward this enhancement

**Comment by sclevine** [comment]
This should work now! The Ruby buildpack will use whatever version of Node.js is supplied by the Node.js buildpack. Just specify the Node.js buildpack before the Ruby buildpack when you push with the `cf v3-push` command.

I'm closing this issue as resolved, but let me know if you run into trouble.
