### ISSUE TITLE
Error when using v1.7.1 and v1.7.2

### ISSUE THREAD

**Issue by Showard180** [cloudfoundry/ruby-buildpack#87]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "http://support.cloudfoundry.com",
   "version": 0,
   "description": "",
   "authorization_endpoint": "",
   "token_endpoint": "",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.81.0",
   "app_ssh_endpoint": "",
   "app_ssh_host_key_fingerprint": "",
   "app_ssh_oauth_client": "ssh-proxy",
   "logging_endpoint": "",
   "doppler_logging_endpoint": "",
   "user": ""
}
cf version 6.22.2-nimbus-e480663-2016-11-15
```
(I have taken some of the details out of this)

What version of the buildpack you are using?
1.7.2 but I'm experiencing the issue with any 1.7 version

If you were attempting to accomplish a task, what was it you were attempting to do?
Push my app using the new version to get the security patch for rubygems

What did you expect to happen?
The server to run as it does with v1.6.10

What was the actual behaviour?
The server exited with this error on start.
```
2017-09-25T12:44:30.13+0100 [API/1]      OUT App instance exited with guid 1694f25c-5a5d-4215-806a-20e450400ac4 payload: {"instance"=>"1efbbf08-6814-4b2c-51c9-6613", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1506339870006043217, "version"=>"ec1d5567-5e70-4513-8f96-9a579fd825e1"}
2017-09-25T12:44:28.95+0100 [APP/PROC/WEB/1]ERR SyntaxError: /home/vcap/app/bin/bundle:2: syntax error, unexpected tSTRING_BEG
2017-09-25T12:44:28.95+0100 [APP/PROC/WEB/1]ERR exec $DEPS_DIR/0/bin/bundle "$@"
```

I am using ruby-1.9.3 with jruby-1.7.26 and have also tried it with ruby 2.3.3 and jruby-9.1.13.0 - the same error happens.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by idoru** [comment]
Hi @Showard180 thanks for submitting this issue. Does the app you're pushing contain a Procfile? If so, would you be able to share it?

**Comment by sclevine** [comment]
Also, please provide any custom start command you may be setting via manifest.yml or via the `cf push` command.

If it's possible for you to put together a complete sample app that demonstrates the failure, it would be very helpful for us.

**Comment by Showard180** [comment]
Here's my `manifest.yml` file:
```
---
applications:
- name: appointment-proxy
  memory: 768M
  instances: 2
  buildpack: https://github.com/cloudfoundry/ruby-buildpack#v1.7.2
  command: jruby -S bundle exec rackup -p $PORT
```

and here's my Procfile:
```
web: jruby -S bundle exec rackup -p $PORT
```

I will work on getting a sample app together today that demonstrates this issue

**Comment by Showard180** [comment]
I've created the a really simple sample app where I am also experiencing the issue.

https://github.com/Showard180/sample-jruby-app

**Comment by Showard180** [comment]
@sclevine @idoru Is there any update on the above?

**Comment by dgodd** [comment]
@Showard180 I believe the rubygems version for jruby is controlled by the jruby version. We do not force a change of rubygems version on jruby see https://www.pivotaltracker.com/story/show/150884901

When I changed your sample app (above) to jruby 9k 
`ruby '2.3.3', :engine => 'jruby', :engine_version => '9.1.13.0'`
I saw rubygems version `
vcap@1c9c882e-c5f5-4420-5f6c-9efb9ec4da09:~$ which gem
/home/vcap/app/.cloudfoundry/0/bin/gem
vcap@1c9c882e-c5f5-4420-5f6c-9efb9ec4da09:~$ gem --version
2.6.13
```

Were you perhaps doing cf ssh and then gem --version without first loading the `profile.d` scripts? If you did you would see the system ruby's rubygem version, rather than than the version installed by the buildpack.

Certainly on jruby 1.7 the version would be old. I would recommend using jruby 9k.

Hopefully the above helps. If you feel jruby 1.7 should be updated please respond.

**Comment by Showard180** [comment]
I've switched to jruby `9.1.13.0` but I don't really know what you mean by the `profile.d` scripts? I've sshed into the machine and run both `/home/vcap/app/.cloudfoundry/0/profile.d/ruby.sh` and `/home/vcap/app/.cloudfoundry/0/profile.d/jruby.sh` but the ruby one errors with 
```
/home/vcap/app/.cloudfoundry/0/profile.d/ruby.sh: line 13: bundle: command not found
/home/vcap/app/.cloudfoundry/0/profile.d/ruby.sh: line 14: bundle: command not found
```

Any ideas what I'm missing here?

**Comment by dgodd** [comment]
@Showard180 You need to run the profile.d scripts inside the app directory. So directly after ssh-ing in.
```
## Show system gem version (and location)
$ which gem
/usr/bin/gem
$ gem --version
2.5.2

## Use buildpack provided ruby/gem
$ ls
app  deps  logs  staging_info.yml  tmp
$ export DEPS_DIR=$PWD/deps
$ export HOME=$PWD/app
$ cd $HOME
$ ls .profile.d/
000_multi-supply.sh  0_jruby.sh  0_ruby.sh
$ source .profile.d/000_multi-supply.sh
$ source .profile.d/0_jruby.sh
$ source .profile.d/0_ruby.sh
$ which gem
/home/vcap/deps/0/bin/gem
$ gem --version
2.6.13
```

There is a story in the backlog to make it easier to get the apps ENV setup upon cf ssh
https://www.pivotaltracker.com/story/show/146900873

**Comment by Showard180** [comment]
Thanks for all the help @dgodd, however, I'm still having issues. I'm pretty sure I'm following your instructions correctly but I'm still having the same issue. Here's what I'm doing:

```
cf ssh <APP_NAME>
~$ which gem
/usr/bin/gem
~$ gem --version
2.5.2
~$ ls
app  logs  staging_info.yml  tmp
~$ export DEPS_DIR=$PWD/deps
~$ export HOME=$PWD/app
/home/vcap$ cd $HOME
~$ ls .profile.d/
0000_set-deps-dir.sh  000_multi-supply.sh  0_jruby.sh  0_ruby.sh
~$ source .profile.d/000_multi-supply.sh
~$ source .profile.d/0_jruby.sh
~$ source .profile.d/0_ruby.sh
bash: bundle: command not found
bash: bundle: command not found
~$ which gem
/usr/bin/gem
~$ gem --version
2.5.2
```

**Comment by dgodd** [comment]
@Showard180 Sorry I should have guessed you would not have the same CF version as I do. You will note that $PWD/deps does not exist, the following should work (I am doing this from memory)

```
export HOME=$PWD/app
cd $HOME
source .profile.d/0000_set-deps-dir.sh
source .profile.d/000_multi-supply.sh
source .profile.d/0_jruby.sh
source .profile.d/0_ruby.sh

which gem
gem --version
```

**Comment by Showard180** [comment]
Yep, thanks @dgodd that worked perfectly! Should I close this issue now as I'm pretty sure it's working as expected?

**Comment by dgodd** [comment]
I'm glad it all worked for you @Showard180 . I'll close this issue as you suggested

**Comment by lsarni** [comment]
I was using @dgodd solution just fine but now after having push my app once more it stopped working. This is my manifest:
```
services:
  - envios-ya-ort-db
  - compose-for-redis
buildpack: "https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.4"
applications:
  - name: envios-ya-ort
    random-route: true
    memory: 256M
    instances: 1
    command: rails server -p $PORT
  - name: sidekiq-worker
    memory: 256M
    instances: 1
    path: .
    command: bundle exec sidekiq
    no-route: true
    health-check-type: process

```

And if I run [this commands](https://github.com/cloudfoundry/ruby-buildpack/issues/87#issuecomment-335603817) on `cf ssh envios-ya-ort` I get:
```
vcap@4d531c7b-3717-4495-6f27-71ee:~$ export HOME=$PWD/app
vcap@4d531c7b-3717-4495-6f27-71ee:/home/vcap$ cd $HOME
vcap@4d531c7b-3717-4495-6f27-71ee:~$ source .profile.d/0000_set-deps-dir.sh
bash: .profile.d/0000_set-deps-dir.sh: No such file or directory
vcap@4d531c7b-3717-4495-6f27-71ee:~$ source .profile.d/000_multi-supply.sh
vcap@4d531c7b-3717-4495-6f27-71ee:~$ source .profile.d/0_ruby.sh
bash: bundle: command not found
bash: bundle: command not found
vcap@4d531c7b-3717-4495-6f27-71ee:~$
vcap@4d531c7b-3717-4495-6f27-71ee:~$ which gem
/usr/bin/gem
vcap@4d531c7b-3717-4495-6f27-71ee:~$ gem --version
2.5.2
vcap@4d531c7b-3717-4495-6f27-71ee:~$
```

**Comment by dgodd** [comment]
@lsarni Have you recently updated CF? It looks like the profile.d scripts are no longer in that location. If you have a directory `/home/vcap/profile.d` you can use that instead. eg.
```
export HOME=$PWD/app
cd $HOME
source ../profile.d/0000_set-deps-dir.sh
source ../profile.d/000_multi-supply.sh
source ../profile.d/0_ruby.sh
```

**Comment by lsarni** [comment]
@dgodd I'm working on Bluemix, I didn't find out if CF has been recently updated but this commands didn't work either. I don't have a `/home/vcap/profile.d` directory.
```
vcap@21138173-6831-49da-53d0-5c10:~$ export HOME=$PWD/app
vcap@21138173-6831-49da-53d0-5c10:/home/vcap$ cd $HOME
vcap@21138173-6831-49da-53d0-5c10:~$ source ../profile.d/0000_set-deps-dir.sh
bash: ../profile.d/0000_set-deps-dir.sh: No such file or directory
vcap@21138173-6831-49da-53d0-5c10:~$ source ../profile.d/000_multi-supply.sh
bash: ../profile.d/000_multi-supply.sh: No such file or directory
vcap@21138173-6831-49da-53d0-5c10:~$ source ../profile.d/0_ruby.sh
bash: ../profile.d/0_ruby.sh: No such file or directory
vcap@21138173-6831-49da-53d0-5c10:~$
```

**Comment by dgodd** [comment]
@lsarni You should have these files somewhere inside your app or the parent directory. You may have to use `find` to find them.

eg. `find . -name '*ruby.sh'`
