### ISSUE TITLE
Disk quota for BRATs

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/ruby-buildpack#91]
The [disk quota for BRATs is set to 256M](https://github.com/cloudfoundry/ruby-buildpack/blob/master/src/ruby/brats/brats_suite_test.go#L24) which is less than needed for our buildpack.
This causes the pushing of the test app to fail with errors like this:

```
   2018-02-15T17:55:43.28+0200 [CELL/0] ERR tar: ./deps/0/vendor_bundle/jruby/2.3.0/gems/eventmachine-1.0.7-java/lib/em/timers.rb: Cannot open: Disk quota exceeded

```

Would you accept a PR that makes it configurable through env vars or some yaml file (also for [the integration suite](https://github.com/cloudfoundry/ruby-buildpack/blob/master/src/ruby/integration/integration_suite_test.go#L31)) so that we don't have to maintain a fork just for a couple of values? It can still have a default value for it so it will be an optional override.

Being able to configure limits can be useful in many cases (e.g. when adding tests that need more space than the existing ones).

What version of the buildpack you are using? -> The SUSE fork: https://github.com/SUSE/cf-ruby-buildpack/tree/v1.7.7.1

If you were attempting to accomplish a task, what was it you were attempting to do? -> Run BRATs

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message

**Comment by dgodd** [comment]
I would accept something along those lines. Note however that the ruby buildpack includes jruby and those tests need a lot more disk and memory, so if you could take that into account.

**Comment by jimmykarily** [comment]
Yes, jruby is the one that fails. It is happy with 300M (for the time being). We will prepare a PR soon. Stay tuned.

**Comment by dgodd** [comment]
I'm OK if you just bump the size of the disks for the jruby integration tests. If you think a default and env variable is better I'm OK with that, and if you would like to just bump the size of those tests specifically I am also OK with that
