### ISSUE TITLE
Issues with LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by giner** [cloudfoundry/ruby-buildpack#95]
What version of the buildpack you are using?
- v1.7.15

[Documentation](https://docs.cloudfoundry.org/buildpacks/ruby/ruby-tips.html) says:
> Add Custom Libraries
> 
> If your app requires external shared libraries that are not provided by the rootfs or the buildpack, you must place the libraries in an `ld_library_path` directory at the app root.
> 
> Note: You must keep these libraries up-to-date. They do not update automatically.
> 
> The Ruby buildpack automatically adds the directory `<app-root>/ld_library_path` to `LD_LIBRARY_PATH` so that your app can access these libraries at runtime.

However it doesn't say that the buildpack adds the path **only** during **staging** and we have to set LD_LIBRARY_PATH=ld_library_path to start the application successfully.

Also, alternatively the following approach can be used in case of custom directory name `LD_LIBRARY_PATH=mylib:/tmp/app/mylib` however I'm not sure if this should be in documentation as `/tmp/app` prefix may potentially change in future as it had already changed in past (it was /tmp/staged/app).

**Comment by CAFxX** [comment]
This is related to #69, where we are now having the same issue again (`bundle install` fails when compiling the `ruby-oci8` gem).

Briefly discussed over slack: https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1520910979000129
