### ISSUE TITLE
pcf dev v29 [ruby buildpack][community exercises]

### ISSUE THREAD

**Issue by vlaskovic** [cloudfoundry/ruby-buildpack#96]
Team,

I have using the following PCD DEV environment for training purposes:
cf-cli-installer_6.35.0_winx64
pcfdev-v0.29.0_PCF1.11.0-windows

Of the CF Basics of the Community exercises (http://basics-workshop.cloudfoundry.org/labs/debugging/
), I have failed to solve debugging exercise due to the following error(s):

1. cf push debug-app
- without explicitly pointing out a build pack:
  DEPENDENCY MISSING IN MANIFEST: ruby 2.2.8
 !
 !     It looks like you're trying to use ruby 2.2.8.
 !
 !     Unfortunately, that version of ruby is not supported by this buildpack.
 !
 !     The versions of ruby supported in this buildpack are:
 !     - 2.4.1
 !     - 2.4.0
 !     - 2.3.4
 !     - 2.3.3
 !     - 2.2.7
 !     - 2.2.6
 !     - 2.1.9
 !     - 2.1.8
 !
 !     If you need further help, start by reading: https://github.com/cloudfoundry/ruby-buildpack/releases.

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

What did you expect to happen?

What was the actual behavior?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

2. if a deploy as: cf push debug-app -b https://github.com/cloudfoundry/ruby-buildpack#2.4.1 
- what i get in logs is
 2018-03-17T17:18:24.95+0100 [STG/0] OUT Staging...
   2018-03-17T17:18:32.62+0100 [STG/0] ERR Failed to clone git repository at https://github.com/cloudfoundry/ruby-buildpack
   2018-03-17T17:18:32.62+0100 [STG/0] OUT Exit status 1
   2018-03-17T17:18:32.63+0100 [STG/0] ERR Staging failed: Exited with status 1

My buildpacks status:
C:\Users\Slobodanka\Documents\tmns\training\LinuxFoundation\CloudFoundry\community-cf-\code\training-zero-to-hero\06-debugging\debug-app>cf buildpacks
Getting buildpacks...

buildpack               position   enabled   locked   filename
java_buildpack          1          true      false    java-buildpack-offline-v3.13.zip
ruby_buildpack          2          true      false    ruby_buildpack-cached-v1.6.37.zip
nodejs_buildpack        3          true      false    nodejs_buildpack-cached-v1.5.32.zip
go_buildpack            4          true      false    go_buildpack-cached-v1.8.1.zip
python_buildpack        5          true      false    python_buildpack-cached-v1.5.18.zip
php_buildpack           6          true      false    php_buildpack-cached-v4.3.31.zip
staticfile_buildpack    7          true      false    staticfile_buildpack-cached-v1.4.5.zip
binary_buildpack        8          true      false    binary_buildpack-cached-v1.0.11.zip
dotnet-core_buildpack   9          true      false    dotnet-core_buildpack-cached-v1.0.15.zip

May you assist please?

Thank you,
Slobodanka

**Comment by astrieanna** [comment]
Hi @vlaskovic,

To use `ruby-2.2.8`, you will need to push with a more recent buildpack, since the system buildpack version you're using doesn't support `2.2.8`.

You had the url almost correct; the only change is the version number. The url needs the buildpack version number, not the ruby version. This will push with the current ruby buildpack:
```
cf push debug-app -b https://github.com/cloudfoundry/ruby-buildpack#v1.7.16
```

If you had wanted to change you app to be compatible with the older ruby buildpack on your pcfdev, you could change your Gemfile (https://github.com/EngineerBetter/training-zero-to-hero/blob/master/06-debugging/debug-app/Gemfile#L2) to use another version of Ruby, such as `2.4.1`.

Hope that helps! Please reopen if this doesn't work for you.
